version: '3.4'
services:
  swoole:
    container_name: "swoole"
    build:
      context: .
      dockerfile: ./swoole.dockerfile
      args:
        SWOOLE_DOCKER_VERSION: ${SWOOLE_DOCKER_VERSION}
    volumes:
      - "${GITHUB_WORKSPACE}:/guzzle-swoole:rw"
    working_dir: /guzzle-swoole
    ulimits:
      core: -1
    privileged: true
    command: tail -f /etc/group

  php8:
    container_name: "php8"
    build:
      context: .
      dockerfile: ./swoole-php8.dockerfile
      args:
        SWOOLE_DOCKER_VERSION: ${SWOOLE_DOCKER_VERSION}
    volumes:
      - "${GITHUB_WORKSPACE}:/guzzle-swoole:rw"
    working_dir: /guzzle-swoole
    ulimits:
      core: -1
    privileged: true
    command: tail -f /etc/group
